name       : less
version    : '487'
release    : 9
source     :
    - http://www.greenwoodsoftware.com/less/less-487.tar.gz : f3dc8455cb0b2b66e0c6b816c00197a71bf6d1787078adeee0bcf2aea4b12706
license    :
    - GPL-3.0
    - BSD-2-Clause
component  : system.base
summary    : less (file pager)
description: |
    less is a free open-source file pager. It is used to read files, but not modify them.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
