name       : less
version    : '527'
release    : 11
source     :
    - http://www.greenwoodsoftware.com/less/less-527.tar.gz : 4e302ac0435811c10866988e0c0feb6c867626cdd8444ae3428aeb9d6e538f95
license    :
    - GPL-3.0
    - BSD-2-Clause
component  : system.base
summary    : less (file pager)
description: |
    less is a free open-source file pager. It is used to read files, but not modify them.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
