name       : less
version    : '520'
release    : 10
source     :
    - http://www.greenwoodsoftware.com/less/less-520.tar.gz : 7b89ea8e605c242f792594ca81dc89979f3537d8cce578f628329c748004908b
license    :
    - GPL-3.0
    - BSD-2-Clause
component  : system.base
summary    : less (file pager)
description: |
    less is a free open-source file pager. It is used to read files, but not modify them.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
