name       : less
version    : '581.2'
release    : 16
source     :
    - http://www.greenwoodsoftware.com/less/less-581.2.tar.gz : ce34b47caf20a99740672bf560fc48d5d663c5e78e67bc254e616b9537d5d83b
license    :
    - GPL-3.0-only
    - BSD-2-Clause
component  : system.base
summary    : less (file pager)
description: |
    less is a free open-source file pager. It is used to read files, but not modify them.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install

