name       : less
version    : '529'
release    : 12
source     :
    - http://www.greenwoodsoftware.com/less/less-529.tar.gz : dba42cd4c38174b7bd0d426d8a39df2be6bcc1ec18946a4642713290f6bf9a0b
license    :
    - GPL-3.0
    - BSD-2-Clause
component  : system.base
summary    : less (file pager)
description: |
    less is a free open-source file pager. It is used to read files, but not modify them.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
