name       : less
version    : '563'
release    : 15
source     :
    - http://www.greenwoodsoftware.com/less/less-563.tar.gz : ce5b6d2b9fc4442d7a07c93ab128d2dff2ce09a1d4f2d055b95cf28dd0dc9a9a
license    :
    - GPL-3.0-only
    - BSD-2-Clause
component  : system.base
summary    : less (file pager)
description: |
    less is a free open-source file pager. It is used to read files, but not modify them.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install

