name       : less
version    : 481
release    : 8
source     :
    - http://www.greenwoodsoftware.com/less/less-481.tar.gz : 3fa38f2cf5e9e040bb44fffaa6c76a84506e379e47f5a04686ab78102090dda5
license    :
    - GPL-3.0
    - BSD-2-Clause
summary    : less (file pager)
description: |
    less is a free open-source file pager. It is used to read files, but not modify them.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
